# C
COLOR_PURPLE = (180, 0 , 255)
COLOR_YELLOW = (255, 255, 0)

# M
MENU_OPTION = (
    "NOVO JOGO (1 JOGADOR)",
    "NOVO JOGO (2 JOGADORES - COOP)",
    "NOVO JOGO (2 JOGADORES - VS)",
    "PLACAR",
    "SAIR"
)

# W
WIN_WIDTH = 576
WIN_HEIGHT = 324
